# Don't change this! Version used to track needed updates.
version = 0
axeStripParticles = true
axeScrapeParticlesDisplayType = "DEFAULT"
axeWaxOffParticlesDisplayType = "DEFAULT"
boneMealUsingParticles = true
flintAndSteelParticles = true
increasedItemBreakParticles = true
waterEvaporateFromBucketSteam = true
waterBucketUseParticles = true
lavaBucketUseParticles = true
powderSnowBucketUseParticles = true
lingeringPotionClouds = true
splashPotionClouds = true

[itemRarity]
particlesDisplayType = "ON"
particleColorType = "ONLY_COLOR_OVERRIDES"
mixedColorName = true
useItemBorder = true
colorOverrides = [
    [ { type = "tag", value = "#inq:starlight" }, { r = 234, g = 170, b = 249 } ]
]
particleMaxHeight = 1.0
particleMaxSpeed = 1.0
particleDensity = 1.0

[projectiles]
enderPearlTrail = true
xpBottleParticlesDisplayType = "VANILLA"
xpBottleParticlesDensity = 10
eggSmashSoundVolume = 0.5
eggSplatParticles = true
snowballTrailDensity = 0.5
snowballPoofsHaveSnowflakes = true
snowballPoofSoundVolume = 0.3