
#─────────────────────────────────────────────────────────────────────────
# Anywhere that uses entity IDs also supports:
# • Tags (e.g. "#minecraft:skeletons")
# • Comma-separated lists (e.g. "minecraft:zombie,#minecraft:skeletons")
#     Applies the setting to all listed IDs. Can use tags, regular IDs, and negation interchangeably
# • Negation (e.g. "!minecraft:evoker")
#     Useful with lists/tags. Excludes the listed IDs from the setting
#     i.e. "#minecraft:raiders,!minecraft:evoker" (all raid mobs EXCEPT evokers)
# Settings with "//v" will list elements vertically. Removing "//v" will list elements in one line
#─────────────────────────────────────────────────────────────────────────
["Entity Temperature"]
	#─────────────────────────────────────────────────────────────────────────//v
	# List of entities that will insulate the player when riding them
	# A value of 0 provides no insulation; 1 provides full insulation
	# └── Format: [["entity_id", coldResistance, heatResistance], ["entity_id", coldResistance, heatResistance], etc...]
	# ⌄ 
	"Insulated Mounts" = [
	    ["alexscaves:submarine", 1, 0],
	    ["immersive_aircraft:warship", 1, 0],
	    ["immersive_aircraft:cargo_airship", 1, 0],
	    ["immersive_aircraft:airship", 1, 0],
	    ["man_of_many_planes:economy_plane", 1, 0],
	    ["man_of_many_planes:scarlet_biplane", 1, 0],
	    ["immersive_aircraft:biplane", 1, 0]
	]
	#─────────────────────────────────────────────────────────────────────────//v
	# Defines temperature-emitting properties for entities
	# ├── Format: [["entity_id", temperature, range, *units], ["entity_id", temperature, range, *units], etc...]
	# └── [* = optional]
	# • temperature: The temperature emitted by the entity
	# • range: The range of the effect, in blocks
	# • units: (Optional) The units of the temperature value (MC, F, or C). Defaults to MC
	# ⌄ 
	"Entity Temperatures" = []
	#─────────────────────────────────────────────────────────────────────────//v
	# Defines entities that are affected by temperature and the climates they can live in
	# ├── Format: [["entity_id", minTemp, maxTemp, *rate, *units], ["entity_id", minTemp, maxTemp, *rate, *units], etc...]
	# └── [* = optional]
	# • min_temp: The minimum livable temperature, as an offset to the minimum temperature for players
	# • max_temp: The maximum livable temperature, as an offset to the maximum temperature for players
	# • *rate: A multiplier to the rate at which the entity overheats or freezes, based on players' rate
	# • *units: The units used for the min/max temperature values (MC, F, or C). Defaults to MC
	# ⌄ 
	"Entity Climate Settings" = []
	#─────────────────────────────────────────────────────────────────────────
	# Enables the temperature system for entities
	# If disabled, entities will not be harmed by temperature
	# ⌄ 
	"Enable Entity Climates" = false
	#─────────────────────────────────────────────────────────────────────────
	# Enables more precise temperature calculations for entities
	# This option might cause performance issues for large amounts of entities
	# ⌄ 
	"Use Advanced Entity Climates" = false

["Fur Growth & Shedding"]
	#─────────────────────────────────────────────────────────────────────────
	# Defines how often a goat will try to grow its fur, the growth cooldown after shearing, and the chance of it succeeding
	# └── Format: [interval, cooldown, chance]
	# ⌄ 
	"Goat Fur Growth Timings" = [1200, 2400, 0.2]
	#─────────────────────────────────────────────────────────────────────────
	# Defines how often a chameleon will try to shed its skin, the cooldown after shedding, and the chance of it succeeding
	# Format: [interval, cooldown, chance]
	# ⌄ 
	"Chameleon Shedding Timings" = [400, 36000, 0.1]

["Mob Spawning"]
	#─────────────────────────────────────────────────────────────────────────//v
	# Defines the biomes that Chameleons can spawn in
	# └── Format: [["biome_id", weight], ["biome_id", weight], etc...]
	# • biome_id: The ID of the biome, e.g. "minecraft:jungle"
	# • weight: The likelihood for the entity to spawn compared to other entities, higher values mean more common spawns
	# ⌄ 
	"Chameleon Spawn Biomes" = [
	    ["minecraft:bamboo_jungle", 80],
	    ["minecraft:jungle", 80],
	    ["minecraft:sparse_jungle", 35],
	    ["minecraft:desert", 1],
	    ["atmospheric:dunes", 0.75],
	    ["atmospheric:flourishing_dunes", 1.5],
	    ["atmospheric:rocky_dunes", 0.75],
	    ["atmospheric:petrified_dunes", 0.5],
	    ["atmospheric:rainforest", 50],
	    ["atmospheric:sparse_rainforest", 40],
	    ["atmospheric:rainforest_basin", 50],
	    ["atmospheric:sparse_rainforest_basin", 30]
	]
	#─────────────────────────────────────────────────────────────────────────//v
	# Defines the biomes that Chameleons can spawn in
	# └── Format: [["biome_id", weight], ["biome_id", weight], etc...]
	# • biome_id: The ID of the biome, e.g. "minecraft:jungle"
	# • weight: The likelihood for the entity to spawn compared to other entities, higher values mean more common spawns
	# ⌄ 
	"Goat Spawn Biomes" = [
	    ["minecraft:frozen_peaks", 8],
	    ["minecraft:jagged_peaks", 8],
	    ["minecraft:snowy_slopes", 8],
	    ["minecraft:meadow", 3],
	    ["minecraft:windswept_hills", 6],
	    ["minecraft:windswept_forest", 6],
	    ["minecraft:windswept_gravelly_hills", 4],
	    ["minecraft:grove", 5],
	    ["minecraft:stony_peaks", 8]
	]

