
[Items]
	#Allows Gulime and its biome varieties.
	gulime = true
	#Defines the interval in ticks between each Gulime regeneration check
	#Range: > 100
	gulimeTick = 1200
	#Defines the chance of successful Gulime regeneration at each check
	#Range: 0.01 ~ 1.0
	gulimeChance = 0.6
	#Allows Cosmopolitan Cocktail and its enchanted variety.
	cosmopolitanCocktail = true

[Flavors]

	[Flavors."Basic Flavors"]
		#Allows Apple to be crafted into desserts such as ice cream and apply specific mob effects when Neapolitan is installed.
		appleFlavor = true
		#Allows Carrot to be crafted into desserts such as ice cream and apply specific mob effects when Neapolitan is installed.
		carrotFlavor = true
		#Allows Glow Berries to be crafted into desserts such as ice cream and apply specific mob effects when Neapolitan is installed.
		glowBerryFlavor = true

	[Flavors."Compatible Flavors"]
		#Allows Enchanted Fruit to be crafted into desserts such as ice cream and apply specific mob effects when Neapolitan and Quark are installed.
		enchantedFruitFlavor = true
		#Allows Kabloom Pulp to be crafted into desserts such as ice cream and apply specific mob effects when Neapolitan and Habitat are installed.
		kabloomFlavor = true
		#Allows Source Berry to be crafted into desserts such as ice cream and apply specific mob effects when Neapolitan and Ars Nouveau are installed.
		sourceBerryFlavor = true
		#Allows Blisterberry to be crafted into desserts such as ice cream and apply specific mob effects when Neapolitan and Undergarden are installed.
		blisterberryFlavor = true
		#Allows Droopfruit to be crafted into desserts such as ice cream and apply specific mob effects when Neapolitan and Undergarden are installed.
		droopfruitFlavor = true

[Effects]
	#Defines the maximum extra health generated by the Exuberance effect (based on user's max health percentage)
	#Range: 0.1 ~ 1.0
	exuberantMaximum = 0.3
	#Defines the chance of triggering the Vardøgerx's damage doubling effect.
	#Range: 0.01 ~ 1.0
	blisterberryChance = 0.15

[Tweaks]
	#Allows the food modifications for vanilla and compatible mods.
	enableModifications = true

	[Tweaks.Farming]
		#Allows tweaks to some of the recipes in Twilight's Flavours & Delights.
		berryGoodTweaks = true

	[Tweaks.Recipes]
		#Allows tweaks to Neapolitan's recipes for Create machines.
		createNeapolitanRecipeTweaks = true
		#Allows tweaks to some of the recipes in Twilight's Flavours & Delights.
		tfdRecipeTweaks = true
		#Allows tweaks to some of the recipes in Seasonals.
		seasonalsRecipeTweaks = true

