#If enabled, a button to the Diet GUI appears in player inventories.
addButton = true
#The x-position of the Diet GUI button in player inventories.
#Range: -10000 ~ 10000
buttonX = 103
#The y-position of the Diet GUI button in player inventories.
#Range: -10000 ~ 10000
buttonY = -20
#The primary text color of the Diet GUI, as an integer or hexadecimal.
textColor = "#FFFFFF"

