
[Vanilla]

	[Vanilla.metal_ores]
		#If mining ores that normally drop raw ores should grant XP
		"Experienced metal" = true

	[Vanilla.farmland]
		#Whether farmland can be untilled by sneak-right clicking them with a hoe
		"Untillable Farmland" = true

	[Vanilla.dispensers]
		#If dispensers should be able to dispense into cauldrons
		"Dispenser Cauldrons" = true

	[Vanilla.disc]
		#The disc that should be spawned when a jukebox is struck with lightning. Disables if string is "no"
		"Lightning Disc" = "minecraft:music_disc_ward"

	[Vanilla.xp]
		#If placing a block should have a chance to yield experience.
		"Experienced Building" = true
		#Specify n here, where the chance of a block dropping xp is 1/n. Integers only!
		"Building XP chance" = 64
		#If all blocks that are crops should drop experience.
		"Experienced Crops" = true
		#Minimum XP a crop block will drop when broken.
		"Minimum Crop XP" = 0
		#Maximum XP a crop block will drop when broken.
		"Maximum Crop XP" = 1

	[Vanilla.enchantments]
		#If enchantments other than protection should be buffed. Experimental!
		"Erm what the sigma" = false

	[Vanilla.beacons]
		#If status effects given you by beacons should NOT give off potion particles
		"Hidden beacon particles" = false

	[Vanilla."Moss carpet"]
		#Whether Moss Carpets should become replaceable, like tall grass or something idk.
		"Replaceable Moss Carpet" = true

	[Vanilla.Stonecutter]
		#If Woodworks is loaded, whether all sawmill recipes should becomes stonecutter recipes instead.
		"Stonecutter more like woodcutter am I right" = false

[atmospheric]

	[atmospheric.Oranges]
		#If oranges can no longer be jumped on to be broken and to create a vapor cloud
		"Normal Oranges" = true

[farmersdelight]

	[farmersdelight."Knife Enchantments"]
		#If knives should no longer receive the silk touch and efficiency from the enchanting table
		"Unbloated Knife Enchantments" = true

[nethersdelight]

	[nethersdelight.fungus_colonies]
		#If fungus colonies should grow on normal rich soil instead of soul rich soil
		"Rich Fungus" = true

	[nethersdelight.bullet_peppers]
		#If bullet peppers should become unplaceable, thus killing letios plants forever
		"Kill letios plants" = true

	[nethersdelight.magma_cakes]
		#If frogs should become unable to consume magma cakes
		"Magma Cakes Good" = false

[supplementaries]

	[supplementaries.quivers]
		#If processing a quiver in a cutting board will eject all the arrows in that quiver
		"Realistic Quivers" = true

["Alexander Caverns"]

	["Alexander Caverns".Acid]
		#If acid should not corrode copper
		"Good Acid" = true

	["Alexander Caverns"."Cave Maps"]
		#If pathfinder quills should make a based sigma cave map instead of a cringe beta vanilla map
		"I'm sorry I said all that" = false

	["Alexander Caverns"."Biome Treats"]
		#If biome treats should work regardless of hunger
		"Okay Treats" = true

	["Alexander Caverns"."Sack of Sating"]
		#If sacks of sating no longer restore saturation
		"Mid sack of sating" = false

	["Alexander Caverns".Tremorzilla]
		#If tremorzillas should no longer passively break all blocks in its hitbox. Blocks are still broken when the tremorzilla attacks, or with its beam attack.
		"Marginally Less Griefy Tremorzillas" = false

[misc]
	#If interacting with blocks like Flower Pots and Amendment Placeable Books should put the item they contain into your inventory, thus merging with existing stacks, instead of adding it to your hand, which is EXTREMELY ANNOYING
	"Less Annoying Item Reclaim" = true

["Mowzies Mobs"]

	["Mowzies Mobs".Rakes]
		#If hoes should also be able to rake sand. Disabled by default option for my modpack
		"Hoes Rake Sand" = false

["Dungeon's Delight"]

	["Dungeon's Delight"."Brewing and Chewing Wardenzola"]
		#If Wardenzola Dungeons Delight Should be Brewing and Chewingified; this means that they are placeable and have a keg recipe, as well as wedges.
		"Wardenzola Wheel" = false

["John Species"]

	["John Species".Crankbow]
		#The stack size crankbows should have. The formula for the capacity of crankbows is stack size * 2 + capacity enchantment level * stack size.
		#This is for if you use a mod like Bigger Stacks to change the stack size
		"Crankbow stack size " = 64

	["John Species"."Combustion Effect"]
		#If explosions caused by mobs that die with the Species Combustion effect should not any blcks
		"Less combusty combustion" = false

