
#MindfulEating common configuration
[common]

	[common.mode]
		#Whether the saturation bonus is dependent on Diet's mechanics. If false, it will instead be based on the last food eaten. Default: false
		"Proportional Diet" = false
		#Whether the buffs added by the Diet mod are enabled. Default: false
		"Native Diet Buffs" = true
		#The amount exhaustion is reduced by (if the above config is false). Default: 0.75
		"Exhaustion Reduction" = 0.75

	#For multiple food groups, separate groups with a /, for example: fruits/vegetables.
	[common."exhaustion sources"]
		#The food group/s corresponding to the swim exhaustion source. Default: fruits
		"Food Group - swim" = "fruits"
		#The food group/s corresponding to the sprint exhaustion source. Default: vegetables
		"Food Group - sprint" = "vegetables"
		#The food group/s corresponding to the jump exhaustion source. Default: vegetables
		"Food Group - jump" = "vegetables"
		#The food group/s corresponding to the mine exhaustion source. Default: grains
		"Food Group - mine" = "grains"
		#The food group/s corresponding to the attack exhaustion source. Default: proteins
		"Food Group - attack" = "proteins"
		#The food group/s corresponding to the hurt exhaustion source. Default: proteins
		"Food Group - hurt" = "proteins"
		#The food group/s corresponding to the heal exhaustion source. Default: sugars
		"Food Group - heal" = "sugars"
		#The food group/s corresponding to the effect exhaustion source. Default: sugars
		"Food Group - effect" = "sugars"

