
#Potions
[potions]
	#If potions refined using redstone or glowstone should be prefixed with either Lengthy or Potent respectively. (Default = true)
	"Refined Potion Names" = true
	#If potions refined using redstone or glowstone should have unique bottle textures to set them apart. (Default = true)
	"Refined Potion Bottles" = true

