#Define rarity for each item in this list to common rank, must be a resource location name !
#If any item is already defined in another list, it will use the highest rarity first !
item_rarity_common_list = []
#Define rarity for each item in this list to uncommon rank, must be a resource location name !
#If any item is already defined in another list, it will use the highest rarity first !
item_rarity_uncommon_list = [
  "alexscaves:fissile_core",
  "alexscaves:charred_remnant",
  "alexscaves:raygun",
  "alexscaves:uranium_shard",
  "alexscaves:uranium",
  "alexscaves:radrock_uranium_ore",
  "alexscaves:acidic_radrock",
  "alexscaves:radrock",
  "alexscaves:radrock_stairs",
  "alexscaves:radrock_slab",
  "alexscaves:radrock_wall",
  "alexscaves:radrock_bricks",
  "alexscaves:radrock_brick_stairs",
  "alexscaves:radrock_brick_slab",
  "alexscaves:radrock_brick_wall",
  "alexscaves:radrock_chiseled",
  "alexscaves:nuclear_bomb",
  "alexscaves:unrefined_waste",
  "alexscaves:uranium_rod",
  "alexscaves:waste_drum",
  "alexscaves:nuclear_furnace_component",
  "alexscaves:tremorzilla_egg",
  "create:crushed_raw_uranium",
  "enlightened_end:irradium_bricks",
  "enlightened_end:irradium_brick_stairs",
  "enlightened_end:irradium_brick_slab",
  "enlightened_end:irradium_brick_wall",
  "enlightened_end:depleted_irradium_bricks",
  "enlightened_end:depleted_irradium_brick_stairs",
  "enlightened_end:depleted_irradium_brick_slab",
  "enlightened_end:depleted_irradium_brick_wall",
  "enlightened_end:irradium_bar",
  "enlightened_end:depleted_irradium_bar",
  "enlightened_end:raw_irradium_block",
  "enlightened_end:irradium_block",
  "enlightened_end:depleted_irradium_block",
]
#Define rarity for each item in this list to rare rank, must be a resource location name !
#If any item is already defined in another list, it will use the highest rarity first !
item_rarity_rare_list = [
  "spelunkery:raw_lead_nugget",
  "create:crushed_raw_lead",
  "spelunkery:granite_lead_ore",
  "spelunkery:andesite_lead_ore",
  "spelunkery:diorite_lead_ore",
  "minecraft:sculk",
  "minecraft:sculk_vein",
  "minecraft:sculk_sensor",
  "minecraft:calibrated_sculk_sensor",
  "alexsmobs:sculk_boomer",
  "netherexp:sculk_grinder",
  "architects_palette:wardstone_blend",
  "architects_palette:wardstone_brick",
  "architects_palette:wardstone",
  "architects_palette:wardstone_slab",
  "architects_palette:wardstone_stairs",
  "architects_palette:wardstone_wall",
  "architects_palette:chiseled_wardstone",
  "architects_palette:wardstone_bricks",
  "architects_palette:wardstone_brick_slab",
  "architects_palette:wardstone_brick_stairs",
  "architects_palette:wardstone_brick_wall",
  "architects_palette:wardstone_pillar",
  "architects_palette:wardstone_lamp",
  "spelunkery:echo_fork",
  "minecraft:echo_shard",
  "alexsmobs:skreecher_soul",
]
#Define rarity for each item in this list to epic rank, must be a resource location name !
#If any item is already defined in another list, it will use the highest rarity first !
item_rarity_epic_list = [
  "patchouli:guide_book",
  "scriptor:book_of_books",
  "scriptor:spellbook_binder",
  "scriptor:writable_spellbook",
  "scriptor:chalk",
  "scriptor:identify_scroll",
  "scriptor:casting_crystal",
  "scriptor:player_casting_crystal",
  "scriptor:coordinate_casting_crystal",
  "scriptor:spellbook",
  "miningmaster:paragon_helmet",
  "miningmaster:paragon_chestplate",
  "miningmaster:paragon_leggings",
  "miningmaster:paragon_boots",
  "miningmaster:ultima_pickaxe",
  "miningmaster:ultima_axe",
  "miningmaster:ultima_sword",
]
#Define rarity for each item in this list to legendary rank, must be a resource location name !
#If any item is already defined in another list, it will use the highest rarity first !
item_rarity_legendary_list = [
  "netherdungeons:piglins_sword",
  "netherdungeons:piglins_axe",
  "netherexp:jackhammer_fist",
  "undergarden:regalium_crystal",
  "immersive_weathering:enchanted_golden_moss_clump",
  "minecraft:enchanted_golden_apple",
  "galosphere:golden_lichen_cordyceps",
  "bountifulfares:golden_apple_block",
  "minecraft:golden_carrot",
  "minecraft:golden_apple",
  "immersive_weathering:golden_moss_clump",
  "etcetera:golden_eggple",
]
#Define rarity for each item in this list to unique rank, must be a resource location name !
#If any item is already defined in another list, it will use the highest rarity first !
item_rarity_unique_list = [
  "undergarden:forgotten_upgrade_smithing_template",
  "undergarden:forgotten_ingot",
  "undergarden:forgotten_nugget",
  "undergarden:forgotten_battleaxe",
  "undergarden:forgotten_sword",
  "undergarden:forgotten_pickaxe",
  "undergarden:forgotten_axe",
  "undergarden:forgotten_shovel",
  "undergarden:forgotten_shovel",
  "undergarden:forgotten_hoe",
  "undergarden:forgotten_block",
  "undergardendelight:forgotten_knife",
  "quark:forgotten_hat",
  "minecraft:ancient_debris",
  "undergarden:ancient_helmet",
  "undergarden:ancient_chestplate",
  "undergarden:ancient_leggings",
  "species:ancient_pinecone",
  "enlightened_end:ancient_root",
  "alexscaves:ancient_sapling",
  "alexscaves:ancient_leaves",
  "architects_palette:ancient_plating",
  "architects_palette:ancient_plating_slab",
  "architects_palette:ancient_plating_stairs",
  "architects_palette:ancient_plating_wall",
  "architects_palette:ancient_plating_fence",
  "minecraft:netherite_scrap",
  "sullysmod:primitive_knife",
  "sullysmod:copper_cog",
  "sullysmod:amber_encased_bug",
  "sullysmod:golden_belt_buckle",
  "sullysmod:golden_goblet",
  "sullysmod:lost_journal",
  "sullysmod:broken_bowl",
  "sullysmod:lost_bag",
  "sullysmod:dried_cyan_flower",
  "sullysmod:primitive_ring",
  "sullysmod:red_cap",
  "sullysmod:small_dented_helmet",
  "sullysmod:stone_idol",
  "sullysmod:jade_amulet",
  "sullysmod:dried_red_flower",
  "sullysmod:lost_recipe_book",
  "sullysmod:familiar_cube",
  "sullysmod:ominous_tablet",
  "sullysmod:lost_sketchbook",
  "sullysmod:torn_cloth",
  "sullysmod:broken_vase",
  "sullysmod:mysterious_plate",
  "sullysmod:lost_crown",
  "sullysmod:emerald_earring",
  "sullysmod:frog_idol",
  "sullysmod:miners_helmet",
  "sullysmod:petrified_cookie",
  "sullysmod:deepslate_vase",
  "sullysmod:arrowhead",
  "sullysmod:moon_tablet",
  "sullysmod:broken_bottle",
  "sullysmod:rusty_tools",
  "sullysmod:torn_manuscript",
  "sullysmod:metallic_skull",
  "sullysmod:small_geode",
]
#Define rarity for each item in this list to mythic rank, must be a resource location name !
#If any item is already defined in another list, it will use the highest rarity first !
item_rarity_mythic_list = [
  "undergarden:utheric_shard",
  "undergarden:utherium_crystal",
  "undergarden:utherium_sword",
  "undergarden:utherium_pickaxe",
  "undergarden:utherium_axe",
  "undergarden:utherium_shovel",
  "undergarden:utherium_hoe",
  "undergarden:utherium_helmet",
  "undergarden:utherium_chestplate",
  "undergarden:utherium_leggings",
  "undergarden:utherium_boots",
  "undergarden:utherium_block",
  "undergarden:depthrock_utherium_ore",
  "undergarden:shiverstone_utherium_ore",
  "undergarden:tremblecrust_utherium_ore",
  "undergardendelight:utherium_knife",
  "alexscaves:extinction_spear",
  "alexscaves:tectonic_shard",
  "alexscaves:volcanic_core",
  "alexscaves:primal_magma",
]
#Define rarity for each item in this list to god rank, must be a resource location name !
#If any item is already defined in another list, it will use the highest rarity first !
item_rarity_god_list = [
  "netherexp:shotgun_core",
  "alexscaves:dreadbow",
  "undergarden:blood_globule",
  "alexscaves:occult_gem",
  "alexscaves:totem_of_possession",
  "alexscaves:desolate_dagger",
  "alexscaves:darkened_apple",
  "alexscaves:pure_darkness",
  "alexscaves:dark_tatters",
  "alexscaves:forsaken_idol",
  "alexscaves:beholder",
  "netherexp:treacherous_candle",
  "netherexp:treacherous_flame",
  "netherexp:brazier_chest",
  "alexscaves:shadow_silk",
  "alexscaves:hood_of_darkness",
  "alexscaves:cloak_of_darkness",
  "sullysmod:death_whistle",
]
