
[light_sources]
	water_sensitive_check = true
	block_entities = true
	entities = true
	self = true

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				zombie_horse = true
				axolotl = true
				bee = true
				arrow = true
				cow = true
				magma_cube = true
				pig = true
				llama = true
				skeleton = true
				bat = true
				husk = true
				frog = true
				hoglin = true
				experience_bottle = true
				rabbit = true
				silverfish = true
				armor_stand = true
				drowned = true
				experience_orb = true
				dolphin = true
				stray = true
				item = true
				turtle = true
				shulker = true
				salmon = true
				vex = true
				wither_skeleton = true
				piglin_brute = true
				ocelot = true
				item_frame = true
				vindicator = true
				horse = true
				phantom = true
				minecart = true
				evoker = true
				glow_squid = true
				warden = true
				glow_item_frame = true
				squid = true
				parrot = true
				creeper = true
				lightning_bolt = true
				enderman = true
				chicken = true
				donkey = true
				evoker_fangs = true
				tropical_fish = true
				fox = true
				slime = true
				pillager = true
				iron_golem = true
				area_effect_cloud = true
				zombified_piglin = true
				piglin = true
				blaze = true
				endermite = true
				cat = true
				zombie = true
				guardian = true
				ghast = true
				sheep = true
				player = true
				illusioner = true
				pufferfish = true
				potion = true
				wolf = true
				villager = true
				skeleton_horse = true
				fishing_bobber = true
				zombie_villager = true
				tnt_minecart = true
				elder_guardian = true
				small_fireball = true
				polar_bear = true
				strider = true
				painting = true
				cave_spider = true
				witch = true
				snow_golem = true
				cod = true
				spider = true

			[light_sources.settings.entities.habitat]
				passerine = true
				pooka = true

			[light_sources.settings.entities.mowziesmobs]
				umvuthana_raptor = true
				foliaath = true
				umvuthana_follower_raptor = true
				umvuthana = true
				grottol = true
				lantern = true
				ferrous_wroughtnaut = true

			[light_sources.settings.entities.archeryexp]
				diamond_arrow = true
				gold_arrow = true

			[light_sources.settings.entities.alexsmobs]
				murmur_head = true
				kangaroo = true
				blue_jay = true
				skelewag = true
				bone_serpent_part = true
				cachalot_echo = true
				catfish = true
				anteater = true
				laviathan = true
				tasmanian_devil = true
				centipede_tail = true
				cosmic_cod = true
				rhinoceros = true
				comb_jelly = true
				skunk = true
				dropbear = true
				leafcutter_ant = true
				blobfish = true
				lobster = true
				snow_leopard = true
				grizzly_bear = true
				rocky_roller = true
				centipede_head = true
				flutter = true
				orca = true
				maned_wolf = true
				crow = true
				banana_slug = true
				elephant = true
				mosquito_spit = true
				crocodile = true
				stradpole = true
				crimson_mosquito = true
				seal = true
				hammerhead_shark = true
				sunbird = true
				straddler = true
				emu = true
				triops = true
				gazelle = true
				underminer = true
				terrapin = true
				gorilla = true
				flying_fish = true
				platypus = true
				capuchin_monkey = true
				murmur = true
				cockroach = true
				bone_serpent = true
				centipede_body = true
				bald_eagle = true
				seagull = true
				mantis_shrimp = true
				raccoon = true
				fly = true
				giant_squid = true
				toucan = true
				alligator_snapping_turtle = true
				skreecher = true
				cachalot_whale = true
				hummingbird = true
				frilled_shark = true
				bison = true
				warped_toad = true
				sugar_glider = true

			[light_sources.settings.entities.netherexp]
				apparition = true
				ecto_slab = true
				shotgun_pellet = true
				vessel = true
				wisp = true

			[light_sources.settings.entities.xp_jellies]
				titanxpsnail = true
				smallexperiencejellyfish = true
				largeexperiencejellyfish = true
				titanexperiencejellyfish = true

			[light_sources.settings.entities.eidolon]
				giant_skeleton = true
				soulfire_projectile = true
				wraith = true
				slimy_slug = true
				raven = true
				necromancer = true
				zombie_brute = true
				bonechill_projectile = true

			[light_sources.settings.entities.oreganized]
				lead_bolt = true

			[light_sources.settings.entities.magical_relics]
				volatile_fireball = true

			[light_sources.settings.entities.galosphere]
				sparkle = true
				spectator_vision = true
				spectre = true
				berserker = true
				specterpillar = true

			[light_sources.settings.entities.ender_beetles]
				enderbeetle = true
				endermite_queen = true

			[light_sources.settings.entities.darkerdepths]
				body_snatcher = true
				void_soul_knight = true
				void_soul = true

			[light_sources.settings.entities.cloudstorage]
				balloon = true
				balloon_tie = true
				bloviator = true
				badloon = true

			[light_sources.settings.entities.atmospheric]
				tetra = true

			[light_sources.settings.entities.rottencreatures]
				dead_beard = true
				undead_miner = true
				burned = true

			[light_sources.settings.entities.upgrade_aquatic]
				thrasher = true
				lionfish = true
				great_thrasher = true
				pike = true
				nautilus = true
				perch = true

			[light_sources.settings.entities.ribbits]
				ribbit = true

			[light_sources.settings.entities.untagged_mobs]
				sweeper = true
				non_player = true

			[light_sources.settings.entities.quark]
				wraith = true
				forgotten = true
				glass_frame = true
				stoneling = true
				foxhound = true
				flamerang = true
				pickarang = true

			[light_sources.settings.entities.origins]
				enderian_pearl = true

			[light_sources.settings.entities.create]
				stationary_contraption = true
				contraption = true

			[light_sources.settings.entities.autumnity]
				snail = true
				turkey = true

			[light_sources.settings.entities.dungeonnowloading]
				spawner_carrier = true
				chaos_spawner = true
				great_experience_bottle = true
				fairkeeper_serpent_caller = true
				sealed_chaos = true
				scuttle = true
				flame_projectile = true
				repulsor = true

			[light_sources.settings.entities.yungscavebiomes]
				sand_snapper = true
				ice_cube = true

			[light_sources.settings.entities.ohmymeteors]
				meteor_projectile = true

			[light_sources.settings.entities.environmental]
				deer = true
				zebra = true
				yak = true
				reindeer = true
				koi = true
				duck = true

			[light_sources.settings.entities.dimdoors]
				monolith = true
				mask = true

			[light_sources.settings.entities.savage_and_ravage]
				skeleton_villager = true
				executioner = true
				spore_cloud = true
				creepie = true
				griefer = true
				rune_prison = true

			[light_sources.settings.entities.lootr]
				lootr_minecart = true

			[light_sources.settings.entities.aquaculture]
				tuna = true
				jellyfish = true
				bluegill = true
				muskellunge = true
				catfish = true
				tambaqui = true
				pacific_halibut = true
				boulti = true
				rainbow_trout = true
				gar = true
				oak_fish_mount = true
				perch = true
				capitaine = true
				atlantic_halibut = true
				piranha = true
				blackfish = true
				red_grouper = true
				arapaima = true
				bayad = true
				atlantic_herring = true
				pollock = true
				carp = true
				atlantic_cod = true
				brown_trout = true
				synodontis = true
				pink_salmon = true
				smallmouth_bass = true
				minnow = true

			[light_sources.settings.entities.undergarden]
				stoneborn = true
				rotwalker = true
				mog = true
				gloomper = true
				smog_mog = true
				sploogie = true
				rotling = true
				rotbeast = true
				brute = true
				nargoyle = true
				muncher = true
				forgotten = true
				gwib = true
				gwibling = true
				forgotten_guardian = true
				dweller = true
				scintling = true

			[light_sources.settings.entities.caverns_and_chasms]
				peeper = true
				glare = true
				mime = true
				deeper = true
				lost_goat = true

			[light_sources.settings.entities.spawn]
				tuna = true
				sea_cow = true
				octopus = true
				sunfish = true
				ant = true
				hamster = true
				herring = true
				clam = true
				seahorse = true
				angler_fish = true

			[light_sources.settings.entities.spelunkery]
				dust_bunny = true

			[light_sources.settings.entities.sullysmod]
				tortoise = true
				thrown_throwing_knife = true
				lanternfish = true
				piranha = true
				jungle_spider = true
				bouldering_zombie = true

			[light_sources.settings.entities.trials]
				wind_charge = true
				bogged = true

			[light_sources.settings.entities.exposure]
				photograph_frame = true

			[light_sources.settings.entities.windswept]
				chilled = true

			[light_sources.settings.entities.species]
				cliff_hanger = true
				spectre = true
				wicked_fireball = true
				birt = true
				stackatick = true
				limpet = true
				leaf_hanger = true
				bewereager = true
				wraptor = true
				quake = true
				ghoul = true
				deepfish = true
				wicked = true

			[light_sources.settings.entities.wan_ancient_beasts]
				paleontologist = true
				toxlacanth = true

			[light_sources.settings.entities.doom_and_gloom]
				holler = true

			[light_sources.settings.entities.dungeonsdelight]
				cleaver = true

			[light_sources.settings.entities.neapolitan]
				plantain_spider = true

			[light_sources.settings.entities.corpse]
				corpse = true

			[light_sources.settings.entities.fintastic]
				moony = true

			[light_sources.settings.entities.ad_astra]
				corrupted_lunarian = true
				star_crawler = true

