
#Eatable settings
[eatable]
	#List of items
	#Depending on the mode only these items will be made eatable (WHITELIST) or these items will keep their vanilla behaviour (BLACKLIST)
	#If an item is not affected according to the rules above they will keep their vanilla behaviour
	item_list = []
	#List of items
	#These items will be made uneatable while full (Overrides vanilla behaviour)
	uneatable_list = []
	#Mode as explained in other settings
	#Allowed Values: BLACKLIST, WHITELIST
	mode = "BLACKLIST"

