
[misc]
	#Range: 0 ~ 128
	diamond_grindstone_deplete_chance = 20
	enable_rough_gems = true
	enable_raw_nuggets = true
	spelunkery_creative_tab = false
	#Range: 0 ~ 128
	parachute_opening_delay = 10
	enable_mores = true

[slimes]
	slimes_always_friendly = false
	enable_slime_growth = true
	#Range: 1 ~ 127
	slime_growth_chance = 10
	#Range: 1 ~ 127
	slime_growth_max = 5
	slimes_spawn_in_all_caves = true
	create_slimes_in_cauldrons = true
	slimes_friendly_to_players_with_regeneration = true
	#Range: 1 ~ 2400
	slime_eating_cooldown = 150

[utilities]
	sculk_drops_with_shears = true
	#Range: 1 ~ 256
	echo_fork_range = 16
	#Range: 1 ~ 32
	magnet_range = 8
	#Range: 1 ~ 512
	magnetite_range = 64
	#Range: 1 ~ 256
	tuning_fork_range = 128
	#Range: 1 ~ 128
	hammer_and_chisel_charge_time = 20
	#Range: 1 ~ 72000
	echo_fork_cooldown = 600
	#Range: 1 ~ 72000
	echo_glow_duration = 1200

[worldgen]
	stone_stripe_features = true
	dark_forest_portabellas = true
	sporophytes_in_lush_caves = true

[nether_portals_and_portal_fluid]
	flint_and_steel_portal_lighting = true
	portal_destruction_crying_obsidian = true
	portal_creation_sound = true
	portal_destruction_sound = true
	portal_fluid_drinking = true
	instant_teleportation = true
	piglins_give_crying_obsidian = true
	dimensional_tears_from_crying_obsidian = false
	dimensional_tears_from_respawn_anchor = true
	portal_fluid_ocean = false
	end_ocean_bucketable = false

