
#Mod Feature Selection
[feature_selection]
	#Enables all Jade features
	jade = true
	#Enables all petrified wood features
	petrified_wood = true
	#Enables all amber features (if disabled, petrified trees will also be disabled)
	amber = true
	#Enables all tortoise features
	tortoise = true
	#Enables all lanternfish features
	lanternfish = true
	#Enables all piranha features
	piranha = true
	#Enables all bouldering zombie features
	bouldering_zombie = true
	#Enables all jungle spider features
	jungle_spider = true
	#Enables the item stand
	item_stand = true
	#Enables all artifact features
	artifacts = true
	#Enables copper buttons
	copper_buttons = true
	#Enables gem lanterns
	gem_lanterns = true
	#Enables grindstone polishing
	grindstone_polishing = true

	#Mod Potions
	[feature_selection.potions]
		#Enables the bad luck potion
		unluck_potion = false
		#Enables the resistance potion
		resistance_potion = false

	#Ambient effects
	[feature_selection.ambient]
		#Enables the Mountain call ambient sounds
		enable_mountain_calls = true
		#Enables the mysterious eyes in the void
		enable_mysterious_eyes = true

#Other Settings
[other_settings]
	#If the velocity of projectiles bounced off of a Jade block should be based on its previous velocity instead of a static value. [Warning: Experimental] (default = false)
	"Dynamic ricochet velocity" = false

	#Vanilla Spawn Modifications
	[other_settings.vanilla_spawn_modifications]
		#Disables zombie spawning in deepslate levels. This is done to prevent too many zombies spawning in this area, since the Bouldering Zombie spawns there exclusively
		"Disable deepslate zombie spawning" = true
		#Disables spider spawning in jungle biomes. This is done to prevent too many spiders spawning in this area, since the Jungle Spider spawns there exclusively
		"Disable spider spawning in jungles" = false

	#Experimental Entity Modifications
	[other_settings.experimental_entity_modifications]
		#Enables wolves consuming meat when killing an entity, similar to what the piranha does
		"Enable wolves consuming meat" = true

