#The duration of the glowing effect applied by the Marking enchantment. 20 ticks = 1 second.
#The cooldown time is the duration multiplied by 0.8.
#Range: 200 ~ 600
"Marking duration" = 300
#The cooldown time caused by using the Precision enchantment. 20 ticks = 1 second.
#Range: 80 ~ 200
"Precision cooldown" = 80
#The sight range of Ender eyes summoned by the Spotter enchantment.
#Range: 8 ~ 16
"Spotter range" = 10
#The amount of time Ender eyes summoned by the Spotter enchantment remain active. 20 ticks = 1 second.
#The cooldown time is the duration multipled by 1.4.
#Range: 600 ~ 1200
"Spotter duration" = 900

