
#Windswept Content Tweaks
[content]
	#How much durability Wooden Buckets should have
	#Range: 1 ~ 1000
	"Wooden Bucket Durability" = 24
	#The chance that the Bumblebee Music Disc should drop from Beehives and Bee Nests
	#Range: 0.0 ~ 1.0
	"Bumblebee Disc Chance" = 0.01

#Vanilla Gameplay Tweaks
[tweaks]
	#Tall Birch Trees will generate branches growing out the side of the tree
	"Birch Branches" = true
	#All skeletons that spawn in snowy biomes are replaced with strays
	"Strays Only" = true
	#Nerfs Boats ability to go extremely fast when on ice and other slippery blocks; default: false
	"Ice Boat Nerf" = false
	#If the Hitbox for Flowers should be Larger
	"Larger Flower Hitbox" = true
	#If Rabbits should have litters of 1-3
	"Rabbit Litters" = true
	#If Rain should wash away Snow Layers
	"Rain Wash Away Snow" = true
	#If Water in Snowy Biomes should slowly give the Frost Effect
	"Freezing Water" = true

#Tweaks to Windswept Worldgen
[worldgen]
	#Roots will grow under the dirt block below a tree, chestnut trees overhanging logs will grow roots
	"Tree Roots" = true

